config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'events#index'

  get 'events/filter/:filter' => 'events#index', as: :filtred_events
  resources :events do
    resources :regestrations
    resources :likes
  end
  resource :session, only: %i[new create destroy]
  resources :users
  get 'signup' => 'users#new'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :regestrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_event, through: :likes, source: :event


  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: %i[new create]
  
  before_action :require_correct_user, only: %i[edit update destroy]



 
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @regestrations = @user.regestrations
    @liked_event = @user.liked_event
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thnaks for signing up"
    else
      render :new
    end
  end

  def edit
  end

  def update
   if  @user.update(user_params)
   redirect_to @user, notice: 'Account successfully updated'
   else
    render :edit
   end 
  end
  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to events_path, alert: 'Account successfully deleted'
  end


  private
  def require_correct_user
    @user = User.find(params[:id])
    redirect_to events_path unless current_user?(@user)
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
 <%= render 'shared/errors', object: user %>
<%= f.label :name %>
<%= f.text_field :name, autofocus: true %>
<%= f.label :email %>
<%= f.email_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<% if user.new_record? %>
 <%= f.submit "Create Account" %>
 <% else %>
  <%= f.submit "Update Account" %>

 <%end %>
<% end %>

app/views/users/edit.html.erb
<h1>EDIT ACCOUNT </h1>
<%= render  "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User")%></h1>
<ul>
<% @users.each do |user| %>
<li>
<%= link_to  user.name, user %>
created
<%= time_ago_in_words(user.created_at) %> ago
</li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>SIGN UP</h1>
<%= render  "form", user: @user %>

app/views/users/show.html.erb
<section>
<h1><%= @user.name %></h1>
<h2><%=  mail_to(@user.email) %></h2>
<% if current_user?(@user)%>

<div>
 <%= link_to  "EDit ACCOUNT", edit_user_path(@user) %>
 <%= link_to  "Delete", @user, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>
<% if @regestrations.present? %>
<h3>Regestrations</h3>
<% @regestrations.each do |r|%>
<div class="regestration">
 <div class="image">
 <%= link_to main_image(r.event), r.event %>
 </div>
 <div class="name">
 <%= link_to  r.event.name, r.event %>
 </div>

 <div class="date">
 <%= time_ago_in_words(r.created_at) %> ago
 </div>
</div>

<% end %>
<% end %>
<% if @liked_event.present? %>
<h3>Liked events</h3>
<div class="liked_events image">
<% @liked_event.each do |event|%>
<%= link_to main_image(event), event %>
<% end %>

</div>
<% end %>
</section>