config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'events#index'

  get 'events/filter/:filter' => 'events#index', as: :filtred_events
  resources :events do
    resources :regestrations
    resources :likes
  end
  resource :session, only: %i[new create destroy]
  resources :users
  get 'signup' => 'users#new'
end

app/models/event.rb
class Event < ApplicationRecord
  before_save :set_slug
  has_many :regestrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
  has_one_attached :main_image

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :description, length: { minimum: 10 }
  validates :price, numericality: {greater_than_or_equal_to: 0}
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }

  validate :acceptable_image

  scope :past, -> { where('start_at < ?', Time.now).order('start_at') }
  scope :upcaming, -> { where('start_at > ?', Time.now).order('start_at')}
  scope :free, -> { where(price: 0.0).order(:name) }
  scope :recent, ->(_max = 3) { past.limit(3) }

  def free?
    price.blank? || price.zero?
  end

  def sold_out?
    (capacity - regestrations.size).zero?
  end

  def to_param
    slug
  end


private

  def acceptable_image
    return unless main_image.attached?

    unless main_image.blob.byte_size <= 1.megabyte
      errors.add(:main_image, 'Is too big')
    end


    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(main_image.content_type)
      errors.add(:main_image, "Must be JEPG or PNG")
    end
  end

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_signin, except: %i[index show]
  before_action :require_admin, except: %i[index show]
  before_action :set_event, only: %i[show update edit destroy]

  def index
    case params[:filter]
    when 'past'
      @events = Event.past
    when 'free'
      @events = Event.free
    when 'recent'
      @events = Event.recent
    else
      @events = Event.upcaming
    end
  end

  def show
    
    @likers = @event.likers
    @categories = @event.categories 
    if current_user
      @like = current_user.likes.find_by(event_id: @event.id)
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event successfully updated'
    else
      render :edit
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event successfully created'
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
   def set_event
    @event = Event.find_by!(slug: params[:id])
   end
  def event_params
    params.require(:event).permit(:name, :location, :description, :price, :start_at, :capacity, 
                                  :main_image, category_ids: [])
  end
end

app/helpers/events_helper.rb
module EventsHelper

def main_image(event)
  if event.main_image.attached?
     image_tag event.main_image
  else
    image_tag "placeholder" 
  end
end

  def price(event)
    if event.free?
      'FREE'
    else
      number_to_currency(event.price)
    end
  end

  def day_and_time(event)
    event.start_at.strftime('%B %d at %I:%M %P')
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
 <%= render 'shared/errors', object: event %>
<%= f.label :name %>
<%= f.text_field :name, autofocus: true %>
<%= f.label :description %>
<%= f.text_field :description, rows: 5 %>
<%= f.label :location %>
<%= f.text_field :location %>
<%= f.label :price %>
<%= f.number_field :price %>
<%= f.label :start_at %>
<%= f.datetime_select :start_at, {ampm: true}, {class: "datetime"} %>
<%= f.label :capacity %>
<%= f.number_field :capacity %>
<%= f.label :main_image %>
<%= f.file_field :main_image %>

<div class="check_box">
  <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
</div>
 <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>editing <%= @event.name %></h1>
<%= render 'form', event: @event%>

app/views/events/index.html.erb
<section class="events">
<% @events.each do |event| %>
<div class="image">
<%= main_image(event) %>
</div>
<li > <%= link_to event.name, event_path(event) %> </li>
<li> <%= event.location %> </li>
<li> <%= price(event) %></li>
<p> <%= truncate(event.description, length: 35, separator:'') %></p>
<p class="event"><%= day_and_time(event) %></p>
<% end %>
</section>
<% if current_user_admin?%>
<section>
<%= link_to  "New Event", new_event_path %>
</section>
<% end %>

app/views/events/new.html.erb
<h1>Create a new event</h1>
<%= render 'form', event: @event%>

app/views/events/show.html.erb
<section>
<div class="image">
   <%= main_image(@event) %>
   <% if current_user %>
   <div class="likes">
    <%= like_or_unlike(@event, @like) %>
   </div>
   <div class="count">
   <%= @likers.size %>
   </div>
   <%end%>
</div>
<h1> <%= @event.name %> </h1>
<h2> <%= @event.location %> </h2>
<h2> 
<%= pluralize(@event.capacity, "spot")%> &bull;
<%= price(@event) %></h2>
<p> <%= truncate(@event.description, length: 35, separator:'') %></p>
<p><%= day_and_time(@event) %></p>

<div>
<%= register_or_sold_out(@event) %>
<%= link_to  "registrations list", event_regestrations_path(@event) %>

</div>
<aside>
<% if @likers.present?%>
<h4>Liked by</h4>
<ul>
<% @likers.each do |user| %>
<li><%= link_to  user.name, user %></li>
<% end %>

</ul>
<% end %>

</aside>
<section>
<% if @categories.present?%>
<h4>Categories</h4>
<ul>
<% @categories.each do |c| %>
<li><%= c.name %></li>
<% end %>
</ul>
<% end %>
</section>

</section>
<% if current_user_admin? %>
<section>
 <%= link_to  "Edit", edit_event_path(@event), class: 'button' %>
 <%= link_to  "Delete", @event, method: :delete, data: { confirm: 'Are you sure?' } %>
</section>
<%end%>